layout_spectrum: 0.8770139
typography_spectrum: 0.1842105
color:
  saturation: 0.1508168
  lightness: 0.5057044
  brandStrength: 0.8537052
  rhythmicContrast: 0.3301106
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: NEW IMAGE BUILT
